AUI().ready(function(l){function e(){$(".tabs").each(function(b){b=$(this);var a=null;b.find(".nav-tabs a").height("");b.find(".nav-tabs a").each(function(){$(this).find(".title").height()>a&&(a=$(this).find(".title").height())});b.find(".nav-tabs a").height(a);a=null})}function m(){new Date-n<f?setTimeout(m,f):(g=!1,$(".tabs .nav-tabs a").height(""),"none"!=$(".tabs .nav-tabs\x3eli").css("float")&&e())}var c="iPad"==navigator.userAgent.match(/iPad/i)?"iPad":"iPhone"==navigator.userAgent.match(/iPhone/i)?
"iPhone":"Android"==navigator.userAgent.match(/Android/i)?"Android":"BlackBerry"==navigator.userAgent.match(/BlackBerry/i)?"BlackBerry":"null";"iPad"==c||"iPhone"==c?$("html").addClass("ios"):"Android"==c&&$("html").addClass("android");$(".btn-group \x3e .btn").click(function(){$(this).addClass("active").siblings().removeClass("active")});$(".backtotop").click(function(){$("body,html").animate({scrollTop:0},100);return!1});$(".breadcrumb li a:first").length&&(c=$(".breadcrumb li a:first").html().toLowerCase().trim(),
$(".breadcrumb li a:first").html("Home"),$(".breadcrumb li a:first").attr("href","/web/"+c+"/home"));l.use("aui-form-validator",function(b){SHOW_ALL_MESSAGES="showAllMessages";MESSAGE_CONTAINER="messageContainer";b.FormValidator.prototype.printStackError=function(a,d,h){var k=this;k.get(SHOW_ALL_MESSAGES)||(h=h.slice(0,1));d.empty();b.Array.each(h,function(p,t){var r=k.getFieldErrorMessage(a,p),s=k.get(MESSAGE_CONTAINER).addClass(p);d.append(s.html(r));a.ancestor(".input-append")?a.ancestor().append(d):
a.ancestor(".control-group")&&a.ancestor(".control-group").append(d)})}});e();var n,g=!1,f=200;$(window).resize(function(){n=new Date;!1===g&&(g=!0,setTimeout(m,f))});var q=$("#sideNavBar");q.on("show.bs.collapse",".collapse",function(){q.find(".collapse.in").collapse("hide")});0<$("input[type\x3d'checkbox']").size()&&$("input[type\x3d'checkbox']").each(function(){$(this).after("\x3cspan class\x3d'checkBoxIcon'\x3e\x3c/span\x3e")});0<$("input[type\x3d'radio']").size()&&$("input[type\x3d'radio']").each(function(){$(this).after("\x3cspan class\x3d'radioIcon'\x3e\x3c/span\x3e")});
0<$('[data-toggle\x3d"tooltip"]').size()&&$('[data-toggle\x3d"tooltip"]').tooltip();0<$(".loginInside .input-container .inline-alert-container.lfr-alert-container .lfr-alert-wrapper").size()?$(".loginInside").addClass("visible_error"):$(".loginInside").removeClass("visible_error");$(".mobile-mask").mask("9999999999");$(".ca-number-mask").mask("999999999");$(".aadhar-mask").mask("999999999999");$(".postal-mask").mask("999999");$(".advance-payment-mask").mask("99999999999999");$(".aadhar-voter-passport-mask").mask("AAAAAAAAAAAA");
window.hideModalOncePrintIsOver=function(){$("#redirectModal, #gisDeleteModel")&&$("#redirectModal, #gisDeleteModel").hide()};0<$(".yui3-widget.alert.liferayalert").size()&&$(".yui3-widget.alert.liferayalert").attr("role","alert")});Liferay.Portlet.ready(function(l,e){});Liferay.on("allPortletsReady",function(){});
$(document).ready(function(){$(".social_button1").click(function(){$(".social_links").animate({width:"420px"});$(".social_links ul.social_links_ul").css({display:"block"});$(".social_button2").css({display:"block"});$(".social_button1").css({display:"none"});$(".download_app_links").animate({width:"0px"});$(".download_app_links ul.download_app_links_ul").css({display:"none"});$(".download_app_button1").css({display:"block"});$(".download_app_button2").css({display:"none"})});$(".social_button2").click(function(){$(".social_links").animate({width:"0px"});
$(".social_links ul.social_links_ul").css({display:"none"});$(".social_button1").css({display:"block"});$(".social_button2").css({display:"none"})});$(".social_button11").click(function(){$(".social_links1").animate({width:"420px"});$(".social_links1 ul.social_links1_ul").css({display:"block"});$(".social_button21").css({display:"block"});$(".social_button11").css({display:"none"});$(".download_app_links").animate({width:"0px"});$(".download_app_links ul.download_app_links_ul").css({display:"none"});
$(".download_app_button1").css({display:"block"});$(".download_app_button2").css({display:"none"})});$(".social_button21").click(function(){$(".social_links1").animate({width:"0px"});$(".social_links1 ul.social_links1_ul").css({display:"none"});$(".social_button11").css({display:"block"});$(".social_button21").css({display:"none"})});$(".download_app_button1").click(function(){$(".download_app_links").animate({width:"190px"});$(".download_app_links ul.download_app_links_ul").css({display:"block"});
$(".download_app_button2").css({display:"block"});$(".download_app_button1").css({display:"none"});$(".social_links").animate({width:"0px"});$(".social_links ul.social_links_ul").css({display:"none"});$(".social_button1").css({display:"block"});$(".social_button2").css({display:"none"})});$(".download_app_button2").click(function(){$(".download_app_links").animate({width:"0px"});$(".download_app_links ul.download_app_links_ul").css({display:"none"});$(".download_app_button1").css({display:"block"});
$(".download_app_button2").css({display:"none"})})});